version: "3.8"

services:
  testpilot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - testpilot

  testpilot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - testpilot
    depends_on:
      - testpilot-backend

networks:
  testpilot:
    driver: bridge
