name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trivy Scan (Backend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend-image:latest'
          format: 'table'

      - name: Trivy Scan (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend-image:latest'

      - name: Build Docker Images
        run: |
          docker build -t testpilot-backend backend/
          docker build -t testpilot-frontend frontend/

      - name: Push to DockerHub or GitHub Registry
        run: |
          docker tag testpilot-backend <registry>/testpilot-backend
          docker push <registry>/testpilot-backend
